### ISSUE TITLE
Only works with -y Always accept hostkeys if they are unknown.

### ISSUE THREAD

**Issue by dkadioglu** [ribbons/TaskerRsync#50]
The connection only works with the following argument:
```
-e "ssh -y"
```

So any host key, even if changed, will be accepted, which is not secure. As far as I understand it, the key will be read from the file ~/.ssh/known_hosts. However, I don't know, where this file is, and how I can manage to include the host key into the file. I would be thankful for any hint.

**Comment by ribbons** [comment]
Yes, you're right - there isn't currently a way to specify host keys at the moment so `-y` (and the risk of MITM attacks) is the only way of getting it to work at the moment.  My use-case is on my home network which is why I've not got round to it yet but it is very near the top of my list.

As you said, Android doesn't really follow the concept of having a home directory so the app will have to manage this by slightly manipulating the environment but it is already doing that for the private key location so should hopefully be pretty straight-forward.

**Comment by ribbons** [comment]
Fixed by adding the ability to specify known host keys in 1feb12ae07f3608d97f8f2010be540080376330d - this will be included in the next release.
